
-- 1) Use an admin role & make compute available
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SNOWFLAKE_LEARNING_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2) Database & schema
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_LEARNING_DB.PUBLIC;

USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

-- 3) Ensure tables exist with the CORRECT column names
--    IMPORTANT: Use RET_PCT instead of RETURN (RETURN can be troublesome; our DataFrame uses RET_PCT)
CREATE OR REPLACE TABLE STOCK_SILVER (
  SYMBOL STRING,
  DT DATE,
  CLOSE FLOAT,
  VOLUME NUMBER,
  RET_PCT FLOAT
);

CREATE TABLE IF NOT EXISTS STOCK_FORECAST (
  SYMBOL STRING,
  DS DATE,
  YHAT FLOAT,
  YHAT_LOWER FLOAT,
  YHAT_UPPER FLOAT
);

-- 4) Optional: If you previously inserted data and want to keep it,
--    but your table still has a "RETURN" column, you could rename it:
--    (Uncomment ONE of the lines below if needed)
-- ALTER TABLE STOCK_SILVER RENAME COLUMN RETURN TO RET_PCT;
-- ALTER TABLE STOCK_SILVER RENAME COLUMN "RETURN" TO RET_PCT;

-- 5) Create BI-friendly views for the dashboard
CREATE OR REPLACE VIEW V_STOCK_SILVER AS
SELECT SYMBOL, DT, CLOSE, VOLUME, RET_PCT
FROM STOCK_SILVER;

CREATE OR REPLACE VIEW V_STOCK_FORECAST AS
SELECT SYMBOL, DS, YHAT, YHAT_LOWER, YHAT_UPPER
FROM STOCK_FORECAST;

-- 6) Quick checks
SHOW TABLES IN SNOWFLAKE_LEARNING_DB.PUBLIC;
DESCRIBE TABLE STOCK_SILVER;
DESCRIBE TABLE STOCK_FORECAST;



USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();


SHOW TABLES IN SCHEMA SNOWFLAKE_LEARNING_DB.PUBLIC;
SHOW VIEWS  IN SCHEMA SNOWFLAKE_LEARNING_DB.PUBLIC;


SELECT COUNT(*) AS cnt_silver   FROM STOCK_SILVER;
SELECT COUNT(*) AS cnt_forecast FROM STOCK_FORECAST;


SELECT * FROM STOCK_SILVER   ORDER BY SYMBOL, DT LIMIT 20;
SELECT * FROM STOCK_FORECAST ORDER BY SYMBOL, DS LIMIT 20;

SELECT COUNT(*) FROM STOCK_SILVER;

-----------------------------------------


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SNOWFLAKE_LEARNING_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE STOCK_SILVER (
  SYMBOL STRING, DT DATE, CLOSE FLOAT, VOLUME NUMBER, RET_PCT FLOAT
);

CREATE OR REPLACE TABLE STOCK_FORECAST (
  SYMBOL STRING, DS DATE, YHAT FLOAT, YHAT_LOWER FLOAT, YHAT_UPPER FLOAT
);

CREATE OR REPLACE VIEW V_STOCK_SILVER AS
SELECT SYMBOL, DT, CLOSE, VOLUME, RET_PCT FROM STOCK_SILVER;

CREATE OR REPLACE VIEW V_STOCK_FORECAST AS
SELECT SYMBOL, DS, YHAT, YHAT_LOWER, YHAT_UPPER FROM STOCK_FORECAST;

-----------------------------------------------------------------------------


SELECT COUNT(*) FROM STOCK_FORECAST;
SELECT * FROM STOCK_FORECAST ORDER BY SYMBOL, DS LIMIT 20;